// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyClJI1xE6kr8_Eg3sjbobrFZkWLLFP2BD0',
    appId: '1:562668242155:web:84bd5e517e52e5f9192aae',
    messagingSenderId: '562668242155',
    projectId: 'project-08d246f1-d6d3-42e6-a40',
    authDomain: 'project-08d246f1-d6d3-42e6-a40.firebaseapp.com',
    storageBucket: 'project-08d246f1-d6d3-42e6-a40.firebasestorage.app',
    measurementId: 'G-R40MXX6M28',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClJI1xE6kr8_Eg3sjbobrFZkWLLFP2BD0', // Using web key as fallback
    appId: '1:562668242155:android:placeholder',
    messagingSenderId: '562668242155',
    projectId: 'project-08d246f1-d6d3-42e6-a40',
    storageBucket: 'project-08d246f1-d6d3-42e6-a40.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClJI1xE6kr8_Eg3sjbobrFZkWLLFP2BD0', // Using web key as fallback
    appId: '1:562668242155:ios:placeholder',
    messagingSenderId: '562668242155',
    projectId: 'project-08d246f1-d6d3-42e6-a40',
    storageBucket: 'project-08d246f1-d6d3-42e6-a40.firebasestorage.app',
    iosBundleId: 'com.jayashreefoundation.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyClJI1xE6kr8_Eg3sjbobrFZkWLLFP2BD0',
    appId: '1:562668242155:web:84bd5e517e52e5f9192aae',
    messagingSenderId: '562668242155',
    projectId: 'project-08d246f1-d6d3-42e6-a40',
    authDomain: 'project-08d246f1-d6d3-42e6-a40.firebaseapp.com',
    storageBucket: 'project-08d246f1-d6d3-42e6-a40.firebasestorage.app',
    measurementId: 'G-R40MXX6M28',
  );
}
